### ISSUE TITLE
Hazelcast Integration mongodb using existing DB and Collections 

### ISSUE THREAD

**Issue by hendisantika** [hazelcast/hazelcast-code-samples#128]
Hi Again,

What if I already have collection.
How to load Hazelcast Integration mongodb using existing DB and Collections.

I want to implement some predeicate / query on the existing collections.

Thanks

**Comment by gAmUssA** [comment]
@hendisantika have you looked   here https://github.com/hazelcast/hazelcast-code-samples/blob/master/hazelcast-integration/mongodb/src/main/java/com/hazelcast/loader/MongoMapStore.java#L59-L63 ?

**Comment by gAmUssA** [comment]
@hendisantika any updates on this?

**Comment by gAmUssA** [comment]
@hendisantika I will close this one because we didn't hear from you. Feel free to reopen if you don't find the answer to you Q in mentioned links. 

Cheers,
Vik

**Comment by hendisantika** [comment]
OK. I will look forward.
Thanks @gAmUssA
