### ISSUE TITLE
Build fails .... The following artifacts could not be resolved: com.hazelcast:hazelcast-enterprise-all:jar:3.8-SNAPSHOT

### ISSUE THREAD

**Issue by paul-hammant** [hazelcast/hazelcast-code-samples#145]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.822 s
[INFO] Finished at: 2017-01-23T22:01:56-05:00
[INFO] Final Memory: 44M/308M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project enterprise: Could not resolve dependencies for project com.hazelcast.samples.enterprise:enterprise:pom:0.1-SNAPSHOT: The following artifacts could not be resolved: com.hazelcast:hazelcast-enterprise-all:jar:3.8-SNAPSHOT, com.hazelcast:hazelcast-enterprise:jar:3.8-SNAPSHOT, com.hazelcast:hazelcast-enterprise-client:jar:3.8-SNAPSHOT: Failure to find com.hazelcast:hazelcast-enterprise-all:jar:3.8-20170123.161002-1055 in https://repository-hazelcast-l337.forge.cloudbees.com/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of Hazelcast Private Snapshot Repository has elapsed or updates are forced -> [H

**Comment by paul-hammant** [comment]
It is not clear where artifact hazelcast-enterprise-all is made. It is not in the samples repo. It is not in the core repo.

**Comment by hasancelik** [comment]
@paul-hammant, Thanks for your report.

We had an issue with automated build which deploys `hazelcast-enterprise-all.jar`. Currently we fixed this problem and our `hazelcast-code-samples` build is running at Jenkins without problem.
