### ISSUE TITLE
Some errata notes for the PDF book

### ISSUE THREAD

**Issue by zeratul021** [hazelcast/hazelcast-code-samples#20]
First of all - terrific job on the book, many thanks for that. Now to the point:

* Chapter 5.6 kind of duplicate content around "maximum number of backups"
* Chapter 5.10.3 typos in words: "opertunity" and "prevens"
* Chapter 5.16 text is missing/cut-off after "...record it owns, e.g. by adding the"
* Chapter 7.3 text is missing/cut-off after "...subscribers that they"
* Chapter 9.1 camelCase in "Imap"
* Chapter 9.5.1 typo in word: "outout"

**Comment by mesutcelik** [comment]
@pveentjer, 
Can we close this?

**Comment by gAmUssA** [comment]
@Serdaro, could you make sure, we have this is fixed already and close this?

**Comment by Serdaro** [comment]
Latest edition has these issues fixed.
