### ISSUE TITLE
XSD file not found

### ISSUE THREAD

**Issue by Guillaume-Mayer** [hazelcast/hazelcast-code-samples#213]
The file http://www.hazelcast.com/schema/spring/hazelcast-spring.xsd used in the spring example file, is not found (error 404).

What is the right file ?

**Comment by googlielmo** [comment]
Hi @Guillaume-Mayer 
The XSD is meant to be retrieved from the classpath, i.e., from either`hazelcast-spring.jar` (or `hazelcast-all.jar`). See http://docs.hazelcast.org/docs/3.9.2/manual/html-single/index.html#enabling-spring-integration (see also the Troubleshooting section).

**Comment by Guillaume-Mayer** [comment]
Thanks, I didn't know that the xsd files were in the classpath.
It works fine, but Eclipse still shows me an xml error (saw 301 moved permanently), is there a way to tell it to look on the classpath ?

**Comment by googlielmo** [comment]
Yes, you should be able to edit the XML catalog in Eclipse in order to map a URL to a local resource, see
https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.wst.xmleditor.doc.user%2Ftopics%2Ftxmlcat.html

**Comment by googlielmo** [comment]
Closing this as the original question was answered. Thanks and feel free to open a new issue anytime.

**Comment by Guillaume-Mayer** [comment]
Thank you, great help!
