### ISSUE TITLE
The Hazelcast client from the Spring Boot/Eureka code samples does not work

### ISSUE THREAD

**Issue by alinbutura** [hazelcast/hazelcast-code-samples#224]
Had an attempt to use the samples provided here: https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/springboot-eureka-partition-groups.
Everything goes well, meaning the hazelcast servers register correctly within eureka server, the eureka client works fine, but my-hazelcast-client app is not able to find any of the service instances registered within Eureka. The last logged line from this client is:

`discoverNodes(): Hazelcast lookup to Eureka: start`

While debugging, I see that:

my-eureka-client is autowiring a `org.springframework.cloud.netflix.eureka.EurekaDiscoveryClient` containing as eurekaClient a `org.springframework.cloud.netflix.eureka.CloudEurekaClient` object
my-hazelcast-client (the faulty one) gets a com.sun.proxy.$Proxy object with toString() returning "Collecting data...".

Can you help?

**Comment by neilstevenson** [comment]
Closing along with https://github.com/hazelcast/hazelcast-code-samples/issues/225
Has been fixed by PR https://github.com/hazelcast/hazelcast-code-samples/pull/413
