### ISSUE TITLE
No code sample for IndexAwarePredicate

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-code-samples#339]
We should consider adding code samples for IndexAwarePredicate. Custom predicates need to implement IndexAwarePredicate if the user wants to add an index.

Related: https://github.com/hazelcast/hazelcast-reference-manual/issues/711

**Comment by mmedenjak** [comment]
Since 4.0, `IndexAwarePredicate` is no longer public - https://github.com/hazelcast/hazelcast/pull/15142

**Comment by burakcelebi** [comment]
Thanks @mmedenjak! I did not know it, let me close this then. 

What about the Custom predicates use case? How to use them with an index starting from 4.0?

**Comment by mmedenjak** [comment]
Custom predicates will not be able to use indexes. See reasoning: https://hazelcast.slack.com/archives/CHN16AMJ5/p1558694099001500

**Comment by burakcelebi** [comment]
Thanks Matko!
