### ISSUE TITLE
Solace example is broken

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast-code-samples#373]
https://github.com/hazelcast/hazelcast-code-samples/tree/master/enterprise/wan-replication/src/main/resources

Solace configuration xml is broken.
Let's decide what to do with this. If we don't support Solace anymore, remove example.

**Comment by mmedenjak** [comment]
Yes, the [solace plugin](https://github.com/hazelcast/hazelcast-solace) was intentionally not updated for 4.0. If we see requests, we will update it. For now, the code sample should be removed.
