### ISSUE TITLE
More sample code

### ISSUE THREAD

**Issue by shlomicthailand** [hazelcast/hazelcast-code-samples#39]
Hi
i think hazelcast docs and even this sample app are lacking the explanation of how to configure the cache in terms of LRU Time to leave etc. eventually i understood that i define a map and its name is the cache name - but that was just a hunch.
also you need to add some more programmatic ways to cache and evict code, specially with spring-cache
as i mentioned injecting the cacheManager then getCache(mapName) and the be able to put/get on it.

what i mean is that an example with only Cacheable("city") is not enough to understand the connection between spring and hazelcast map.

thanks you have a wonderful product.

Shlomi

**Comment by noctarius** [comment]
I guess you're talking about caches for the Spring Framework, don't you?

**Comment by shlomicthailand** [comment]
yes spring cache abstraction. 
sometimes annotations are not enough , and also its kind of a magic when you don't specify a map name and use the cache name in cacheable annotation (e.g city)

**Comment by mesutcelik** [comment]
closed via #76
