### ISSUE TITLE
How To use group in version 4.0.1

### ISSUE THREAD

**Issue by lihuanyu-java** [hazelcast/hazelcast-code-samples#421]
EurekaOneDiscoveryStrategyFactory.setEurekaClient(eurekaClient);
        Config config = new Config();
        config.getGroupConfig().setName("business");
        config.setInstanceName("business-instance");

getGroupConfig was canceled in 4.0.1 ,how to work it

**Comment by neilstevenson** [comment]
`GroupConfig` of name & password was changed in the move from 3.* to 4.* to be `ClusterConfig` and just a name.

So `config.setClusterName("business")` should do it. See https://docs.hazelcast.org/docs/4.0.1/javadoc/com/hazelcast/config/Config.html#setClusterName-java.lang.String-

The "_password_" field was badly named and deprecated - see https://github.com/hazelcast/hazelcast/issues/11667.

**Comment by mmedenjak** [comment]
Closing as resolved. Please also refer to the migration guide for 4.0 - https://docs.hazelcast.org/docs/4.0/manual/html-single/#replacing-code-group-code-by-simple-cluster-name-configuration.
