### ISSUE TITLE
DistributedObjectDestroyedException: AtomicValue[xxx] is already destroyed!

### ISSUE THREAD

**Issue by jalberti** [hazelcast/hazelcast-code-samples#456]
How do we destroy an CP object, to release memory, and then later create another instance reusing the same name? Reviewing this https://github.com/hazelcast/hazelcast/blob/07fa8c5bbbfe5e48d1f488150e02bcdba326f8d1/hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/spi/atomic/RaftAtomicValueService.java#L158 it seems like there is a node local map that holds the keys of all destroyed references? I might have overlooked something, but ...

1) The map/set which holds the keys of old destroyed objects grows forever? How does this not constitute a memory leak, I do not see this being cleaned up ever?
2) I do not see a reason why one would need this guard? If an CP object is destroyed, and then re-created, there is no harm, it is a CP object after all? There could be a race, and the destroy arrives after the re-create, to protect against this one could use a compare-and-set style destroy, i.e. only allow the destroy if the value of the object is known?

As it stands today it seems like the CP system is unusable for scenarios where consistent objects are required, not for the lifetime of the cluster, but only for the lifetime of the object? What am I missing? Thanks!

**Comment by mmedenjak** [comment]
Hi @jalberti , as you've probably figured out, it's not safe to reuse a destroyed CP object once it's been destroyed. That's probably the reason why we need to keep some track of which instances were destroyed and which are still alive. I don't think it has anything to do with our design decisions as it's more of a fundamental rule of safety.
