### ISSUE TITLE
Getting memory leak error when upgrading hazelcast version to 3.11 from 3.10.7

### ISSUE THREAD

**Issue by dipyadav1** [hazelcast/hazelcast-code-samples#547]
SEVERE [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [coupon] created a ThreadLocal with key of type [com.amazonaws.util.XmlUtils$1] (value [com.amazonaws.util.XmlUtils$1@51a8c509]) and a value of type [com.ctc.wstx.stax.WstxInputFactory] (value [com.ctc.wstx.stax.WstxInputFactory@5f358107]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Comment by frant-hartm** [comment]
Hi,

this repository is for code samples.

For issues with hazelcast please use this repository https://github.com/hazelcast/hazelcast

On top of that versions 3.
